version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: transaction-db
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5445:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
